services:
    app:
        image: ghcr.io/usetrmnl/byos_laravel:latest
        ports:
            - "4567:8080"
        environment:
            #- APP_KEY=
            - PHP_OPCACHE_ENABLE=1
            - TRMNL_PROXY_REFRESH_MINUTES=15
        volumes:
           - database:/var/www/html/database/
           - storage:/var/www/html/storage
        restart: unless-stopped
volumes:
    database:
    storage:

